# Generated by Django 3.2 on 2024-10-29 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20241029_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150, validators=[django.core.validators.MaxLengthValidator(150)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=150, validators=[django.core.validators.MaxLengthValidator(150)]),
            preserve_default=False,
        ),
    ]
